In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/t-shirts-sizes/tshirt-sizing.csv


## Imports Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

## Read Data

In [3]:
df = pd.read_csv('/kaggle/input/t-shirts-sizes/tshirt-sizing.csv')
df.head(10)

Height (in cms)  Weight (in kgs) T Shirt Size
0              158               58            S
1              158               59            S
2              158               63            S
3              160               59            S
4              160               60            S
5              163               60            S
6              163               61            S
7              160               64            L
8              163               64            L
9              165               61            L

In [4]:
df.sample(10)

Height (in cms)  Weight (in kgs) T Shirt Size
15              170               63            L
3               160               59            S
6               163               61            S
5               163               60            S
10              165               62            L
2               158               63            S
4               160               60            S
11              165               65            L
12              168               62            L
7               160               64            L

## Assign X,Y

In [5]:
x = df.iloc[:,0:2]
y = df.iloc[:,2]


In [6]:
x

Height (in cms)  Weight (in kgs)
0               158               58
1               158               59
2               158               63
3               160               59
4               160               60
5               163               60
6               163               61
7               160               64
8               163               64
9               165               61
10              165               62
11              165               65
12              168               62
13              168               63
14              168               66
15              170               63
16              170               64
17              170               68

In [7]:
y

0     S
1     S
2     S
3     S
4     S
5     S
6     S
7     L
8     L
9     L
10    L
11    L
12    L
13    L
14    L
15    L
16    L
17    L
Name: T Shirt Size, dtype: object

## encoding

In [8]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()
y = encode.fit_transform(y) 
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## data split

In [9]:
X_train , X_test , y_train , y_test = train_test_split(x,y,test_size=.20)

In [10]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train , y_train)

KNeighborsClassifier()

In [11]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, 0])

In [12]:
y_test

array([1, 0, 0, 0])

## Acuracy score between y_test and y_pred

In [13]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

1.0

## Test Errors

In [14]:
test_errors = []

for k in range(1,10):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train , y_train)
    

    y_pred_test = model.predict(X_test)
    error = 1- accuracy_score(y_test , y_pred_test)
    test_errors.append(error)

test_errors

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

## note when K=7 it will be best accuracy